export const routes = {
  home: '/',
  catalog: '/catalog',
  inStock: '/in-stock',
  transit: '/in-transit',
  calculator: '/calculator',
  calculatorOrest: '/calculator/orest',
  calculatorBase: '/calculator-base',
  blog: '/blog',
  cases: '/cases',
  faq: '/faq',
  contacts: '/contacts',
  privacy: '/privacy-policy',
  terms: '/terms-of-use',
  lotDetail: '/lots/:lotId',
} as const
