import type { Locale } from '../../../shared/i18n/messages'
import type { CabinetCarStatus, CabinetPublicationStatus } from '../model/cabinetTypes'

export type CabinetCopy = {
  heroLead: string
  heroMetaLabel: string
  addCar: string
  totalCars: string
  activeCars: string
  readyCars: string
  totalPhotos: string
  searchPlaceholder: string
  allStatuses: string
  emptyList: string
  noSelection: string
  uploadHelp: string
  uploadErrorTooLarge: string
  uploadErrorTooMany: string
  uploadErrorCloud: string
  uploadProcessing: string
  removePhoto: string
  setPrimaryPhoto: string
  primaryPhotoBadge: string
  addPhoto: string
  deleteCar: string
  saveCar: string
  publishCar: string
  previewListing: string
  autoGeneratedHint: string
  duplicateVinWarning: string
  vinDecodeLoading: string
  vinDecodeSuccess: string
  vinDecodePartial: string
  vinDecodeError: string
  syncSaving: string
  syncCloudReady: string
  syncLocalReady: string
  syncLocalFallback: string
  renewListing: string
  renewListingHint: string
  listingExpiredBanner: string
  listingExpiresSoonBanner: string
  sectionIdentity: string
  sectionSpecs: string
  sectionLogistics: string
  sectionCondition: string
  sectionPublication: string
  sectionGallery: string
  sectionNotes: string
  fieldTitle: string
  fieldMake: string
  fieldModel: string
  fieldYear: string
  fieldVin: string
  fieldLotNumber: string
  fieldStockNumber: string
  fieldSourceUrl: string
  fieldAuction: string
  fieldStatus: string
  fieldBodyStyle: string
  fieldBodyCode: string
  fieldGeneration: string
  fieldTrim: string
  fieldColorExterior: string
  fieldColorInterior: string
  fieldEngineVolume: string
  fieldEngineCode: string
  fieldEnginePowerHp: string
  fieldFuelType: string
  fieldDrivetrain: string
  fieldTransmission: string
  fieldMileageKm: string
  fieldOdometerUnit: string
  fieldLocation: string
  fieldCountryOfOrigin: string
  fieldImportDestination: string
  fieldOwnershipType: string
  fieldKeysStatus: string
  fieldStartCondition: string
  fieldDamagePrimary: string
  fieldDamageSecondary: string
  fieldPublicationStatus: string
  fieldPublicTitle: string
  fieldPublicSlug: string
  fieldPublicDescription: string
  fieldPublicPriceUsd: string
  fieldPublicEstimateUsd: string
  fieldPublicBadge: string
  fieldPublicHotOffer: string
  fieldRepairEstimateUsd: string
  fieldTargetBudgetUsd: string
  fieldPurchasePriceUsd: string
  fieldCustomsAndFeesUsd: string
  fieldSellerName: string
  fieldSellerPhone: string
  fieldDescription: string
  fieldServiceHistory: string
  fieldModifications: string
  fieldNotes: string
  photoCountLabel: string
  carCountLabel: string
  statusLabels: Record<CabinetCarStatus, string>
  publicationStatusLabels: Record<CabinetPublicationStatus, string>
}

const copy: Record<Locale, CabinetCopy> = {
  uk: {
    heroLead: 'Ведіть усі свої авто в одному кабінеті: від чернетки та ставок до доставки, ремонту й продажу.',
    heroMetaLabel: 'Керування парком клієнта',
    addCar: 'Додати авто',
    totalCars: 'Усього авто',
    activeCars: 'Активні в роботі',
    readyCars: 'Готові / завершені',
    totalPhotos: 'Фото в архіві',
    searchPlaceholder: 'Пошук за VIN, моделлю, лотом або нотатками',
    allStatuses: 'Усі статуси',
    emptyList: 'Поки немає авто. Створіть першу картку і почніть збирати повний профіль машини.',
    noSelection: 'Оберіть авто зліва або створіть нове, щоб заповнити повну картку.',
    uploadHelp: 'До 12 фото, максимум 5 МБ за файл. Перед збереженням ми стискаємо зображення до оптимального веб-формату.',
    uploadErrorTooLarge: 'Одне або кілька фото перевищують 5 МБ.',
    uploadErrorTooMany: 'Можна зберігати не більше 12 фото на авто.',
    uploadErrorCloud: 'Не вдалося завантажити фото в хмару. Якщо Supabase недоступний, фото залишаться лише локально.',
    uploadProcessing: 'Обробляємо та стискаємо фото...',
    removePhoto: 'Видалити',
    setPrimaryPhoto: 'Зробити головним',
    primaryPhotoBadge: 'Головне фото',
    addPhoto: 'Додати фото',
    deleteCar: 'Видалити авто',
    saveCar: 'Зберегти авто',
    publishCar: 'Опублікувати авто',
    previewListing: 'Переглянути оголошення',
    autoGeneratedHint: 'Поле заповнюється автоматично',
    duplicateVinWarning: 'Увага: такий VIN уже є в іншій картці.',
    vinDecodeLoading: 'Декодуємо VIN і шукаємо характеристики авто...',
    vinDecodeSuccess: 'VIN розпізнано. Порожні поля заповнено автоматично.',
    vinDecodePartial: 'VIN розпізнано частково. Для європейських авто NHTSA інколи повертає не всі поля.',
    vinDecodeError: 'Не вдалося отримати надійні дані по VIN. Перевірте VIN або заповніть характеристики вручну.',
    syncSaving: 'Зберігаємо зміни...',
    syncCloudReady: 'Синхронізація з Supabase активна',
    syncLocalReady: 'Локальний режим збереження',
    syncLocalFallback: 'Хмара недоступна, тимчасово працюємо локально',
    renewListing: 'Продовжити публікацію',
    renewListingHint: 'Оголошення буде активним ще 41 день',
    listingExpiredBanner: 'Термін дії оголошення закінчився. Продовжте, щоб знову показати авто.',
    listingExpiresSoonBanner: 'Оголошення скоро закінчується. Продовжте публікацію, щоб не втратити видимість.',
    sectionIdentity: 'Ідентифікація авто',
    sectionSpecs: 'Технічні характеристики',
    sectionLogistics: 'Купівля та логістика',
    sectionCondition: 'Стан і комплектність',
    sectionPublication: 'Публікація в авто в наявності',
    sectionGallery: 'Фото та візуальна фіксація',
    sectionNotes: 'Опис, історія та нотатки',
    fieldTitle: 'Назва картки',
    fieldMake: 'Марка',
    fieldModel: 'Модель',
    fieldYear: 'Рік',
    fieldVin: 'VIN',
    fieldLotNumber: 'Номер лота',
    fieldStockNumber: 'Внутрішній номер',
    fieldSourceUrl: 'Посилання на джерело',
    fieldAuction: 'Аукціон / майданчик',
    fieldStatus: 'Статус',
    fieldBodyStyle: 'Тип кузова',
    fieldBodyCode: 'Код кузова',
    fieldGeneration: 'Покоління',
    fieldTrim: 'Комплектація',
    fieldColorExterior: 'Колір кузова',
    fieldColorInterior: 'Колір салону',
    fieldEngineVolume: 'Об’єм двигуна',
    fieldEngineCode: 'Код двигуна',
    fieldEnginePowerHp: 'Потужність, к.с.',
    fieldFuelType: 'Тип пального',
    fieldDrivetrain: 'Привід',
    fieldTransmission: 'Коробка передач',
    fieldMileageKm: 'Пробіг',
    fieldOdometerUnit: 'Одиниця пробігу',
    fieldLocation: 'Локація авто',
    fieldCountryOfOrigin: 'Країна походження',
    fieldImportDestination: 'Країна призначення',
    fieldOwnershipType: 'Тип власності',
    fieldKeysStatus: 'Ключі',
    fieldStartCondition: 'Стан запуску',
    fieldDamagePrimary: 'Основне пошкодження',
    fieldDamageSecondary: 'Додаткове пошкодження',
    fieldPublicationStatus: 'Статус публікації',
    fieldPublicTitle: 'Публічний заголовок',
    fieldPublicSlug: 'Публічний slug',
    fieldPublicDescription: 'Короткий опис для каталогу',
    fieldPublicPriceUsd: 'Публічна ціна, USD',
    fieldPublicEstimateUsd: 'Орієнтир ціни, USD',
    fieldPublicBadge: 'Бейдж / мітка',
    fieldPublicHotOffer: 'Позначити як hot offer',
    fieldRepairEstimateUsd: 'Оцінка ремонту, USD',
    fieldTargetBudgetUsd: 'Цільовий бюджет, USD',
    fieldPurchasePriceUsd: 'Ціна купівлі, USD',
    fieldCustomsAndFeesUsd: 'Мито та збори, USD',
    fieldSellerName: 'Продавець / контакт',
    fieldSellerPhone: 'Телефон продавця',
    fieldDescription: 'Короткий опис авто',
    fieldServiceHistory: 'Сервісна історія',
    fieldModifications: 'Модифікації та тюнінг',
    fieldNotes: 'Нотатки менеджера',
    photoCountLabel: 'фото',
    carCountLabel: 'авто',
    statusLabels: {
      draft: 'Чернетка',
      research: 'Аналіз',
      bidding: 'В обробці',
      won: 'Викуплено',
      shipping: 'Логістика',
      repair: 'Ремонт',
      ready: 'Готово',
      sold: 'Продано',
    },
    publicationStatusLabels: {
      private: 'Приватно',
      published: 'Опубліковано',
      pending_transit: 'На перевірці (в дорозі)',
      pending_stock: 'На перевірці (в наявності)',
      rejected: 'Відхилено',
    },
  },
  en: {
    heroLead: 'Manage every client car in one cabinet, from draft and bidding to shipping, repair, and sale.',
    heroMetaLabel: 'Client fleet workspace',
    addCar: 'Add car',
    totalCars: 'Total cars',
    activeCars: 'Active pipeline',
    readyCars: 'Ready / finished',
    totalPhotos: 'Photos stored',
    searchPlaceholder: 'Search by VIN, model, lot, or notes',
    allStatuses: 'All statuses',
    emptyList: 'No cars yet. Create the first card and start building a complete vehicle profile.',
    noSelection: 'Select a car on the left or create a new one to fill in the full record.',
    uploadHelp: 'Up to 12 photos, max 5 MB each. Images are compressed before saving into an optimized web format.',
    uploadErrorTooLarge: 'One or more photos are larger than 5 MB.',
    uploadErrorTooMany: 'No more than 12 photos can be stored per car.',
    uploadErrorCloud: 'Could not upload photos to cloud storage. If Supabase is unavailable, photos stay local only.',
    uploadProcessing: 'Processing and compressing photos...',
    removePhoto: 'Remove',
    setPrimaryPhoto: 'Set as primary',
    primaryPhotoBadge: 'Primary photo',
    addPhoto: 'Add photo',
    deleteCar: 'Delete car',
    saveCar: 'Save car',
    publishCar: 'Publish car',
    previewListing: 'Preview listing',
    autoGeneratedHint: 'This field is generated automatically',
    duplicateVinWarning: 'Warning: this VIN already exists in another card.',
    vinDecodeLoading: 'Decoding VIN and looking up vehicle specifications...',
    vinDecodeSuccess: 'VIN decoded. Empty fields were auto-filled.',
    vinDecodePartial: 'VIN decoded partially. For many European vehicles, NHTSA returns only part of the spec.',
    vinDecodeError: 'Could not fetch reliable VIN data. Check the VIN or fill specifications manually.',
    syncSaving: 'Saving changes...',
    syncCloudReady: 'Supabase sync active',
    syncLocalReady: 'Local save mode',
    syncLocalFallback: 'Cloud unavailable, temporarily saving locally',
    renewListing: 'Renew listing',
    renewListingHint: 'Listing will be active for another 41 days',
    listingExpiredBanner: 'This listing has expired. Renew it to show the car again.',
    listingExpiresSoonBanner: 'This listing expires soon. Renew to keep it visible.',
    sectionIdentity: 'Vehicle identity',
    sectionSpecs: 'Technical specification',
    sectionLogistics: 'Purchase and logistics',
    sectionCondition: 'Condition and completeness',
    sectionPublication: 'Publish to in-stock inventory',
    sectionGallery: 'Photo gallery and visual record',
    sectionNotes: 'Description, history, and notes',
    fieldTitle: 'Card title',
    fieldMake: 'Make',
    fieldModel: 'Model',
    fieldYear: 'Year',
    fieldVin: 'VIN',
    fieldLotNumber: 'Lot number',
    fieldStockNumber: 'Internal stock number',
    fieldSourceUrl: 'Source URL',
    fieldAuction: 'Auction / source',
    fieldStatus: 'Status',
    fieldBodyStyle: 'Body style',
    fieldBodyCode: 'Body code',
    fieldGeneration: 'Generation',
    fieldTrim: 'Trim',
    fieldColorExterior: 'Exterior color',
    fieldColorInterior: 'Interior color',
    fieldEngineVolume: 'Engine volume',
    fieldEngineCode: 'Engine code',
    fieldEnginePowerHp: 'Power, hp',
    fieldFuelType: 'Fuel type',
    fieldDrivetrain: 'Drivetrain',
    fieldTransmission: 'Transmission',
    fieldMileageKm: 'Mileage',
    fieldOdometerUnit: 'Mileage unit',
    fieldLocation: 'Vehicle location',
    fieldCountryOfOrigin: 'Country of origin',
    fieldImportDestination: 'Destination country',
    fieldOwnershipType: 'Ownership type',
    fieldKeysStatus: 'Keys status',
    fieldStartCondition: 'Start condition',
    fieldDamagePrimary: 'Primary damage',
    fieldDamageSecondary: 'Secondary damage',
    fieldPublicationStatus: 'Publication status',
    fieldPublicTitle: 'Public title',
    fieldPublicSlug: 'Public slug',
    fieldPublicDescription: 'Short catalog description',
    fieldPublicPriceUsd: 'Public price, USD',
    fieldPublicEstimateUsd: 'Price estimate, USD',
    fieldPublicBadge: 'Badge / label',
    fieldPublicHotOffer: 'Mark as hot offer',
    fieldRepairEstimateUsd: 'Repair estimate, USD',
    fieldTargetBudgetUsd: 'Target budget, USD',
    fieldPurchasePriceUsd: 'Purchase price, USD',
    fieldCustomsAndFeesUsd: 'Customs and fees, USD',
    fieldSellerName: 'Seller / contact',
    fieldSellerPhone: 'Seller phone',
    fieldDescription: 'Short vehicle description',
    fieldServiceHistory: 'Service history',
    fieldModifications: 'Modifications and tuning',
    fieldNotes: 'Manager notes',
    photoCountLabel: 'photos',
    carCountLabel: 'cars',
    statusLabels: {
      draft: 'Draft',
      research: 'Research',
      bidding: 'Processing',
      won: 'Won',
      shipping: 'Shipping',
      repair: 'Repair',
      ready: 'Ready',
      sold: 'Sold',
    },
    publicationStatusLabels: {
      private: 'Private',
      published: 'Published',
      pending_transit: 'Pending review (in transit)',
      pending_stock: 'Pending review (in stock)',
      rejected: 'Rejected',
    },
  },
  pl: {
    heroLead: 'Prowadź wszystkie auta klienta w jednym panelu: od szkicu i licytacji po transport, naprawę i sprzedaż.',
    heroMetaLabel: 'Przestrzeń floty klienta',
    addCar: 'Dodaj auto',
    totalCars: 'Wszystkie auta',
    activeCars: 'Aktywne w procesie',
    readyCars: 'Gotowe / zakończone',
    totalPhotos: 'Zdjęcia w archiwum',
    searchPlaceholder: 'Szukaj po VIN, modelu, locie lub notatkach',
    allStatuses: 'Wszystkie statusy',
    emptyList: 'Nie ma jeszcze aut. Dodaj pierwszą kartę i zacznij budować pełny profil pojazdu.',
    noSelection: 'Wybierz auto z listy po lewej albo utwórz nowe, aby uzupełnić pełną kartę.',
    uploadHelp: 'Do 12 zdjęć, maksymalnie 5 MB każde. Przed zapisem kompresujemy obrazy do zoptymalizowanego formatu.',
    uploadErrorTooLarge: 'Jedno lub kilka zdjęć przekracza 5 MB.',
    uploadErrorTooMany: 'Na jedno auto można zapisać maksymalnie 12 zdjęć.',
    uploadErrorCloud: 'Nie udało się wysłać zdjęć do chmury. Jeśli Supabase jest niedostępny, zdjęcia pozostaną tylko lokalnie.',
    uploadProcessing: 'Przetwarzamy i kompresujemy zdjęcia...',
    removePhoto: 'Usuń',
    setPrimaryPhoto: 'Ustaw jako główne',
    primaryPhotoBadge: 'Zdjęcie główne',
    addPhoto: 'Dodaj zdjęcie',
    deleteCar: 'Usuń auto',
    saveCar: 'Zapisz auto',
    publishCar: 'Opublikuj auto',
    previewListing: 'Podgląd ogłoszenia',
    autoGeneratedHint: 'To pole jest uzupełniane automatycznie',
    duplicateVinWarning: 'Uwaga: taki VIN już istnieje w innej karcie.',
    vinDecodeLoading: 'Dekodujemy VIN i pobieramy specyfikację pojazdu...',
    vinDecodeSuccess: 'VIN rozpoznany. Puste pola zostały uzupełnione automatycznie.',
    vinDecodePartial: 'VIN rozpoznany częściowo. Dla wielu aut z Europy NHTSA zwraca tylko część danych.',
    vinDecodeError: 'Nie udało się pobrać wiarygodnych danych VIN. Sprawdź numer lub uzupełnij dane ręcznie.',
    syncSaving: 'Zapisujemy zmiany...',
    syncCloudReady: 'Synchronizacja Supabase aktywna',
    syncLocalReady: 'Tryb zapisu lokalnego',
    syncLocalFallback: 'Chmura niedostępna, tymczasowo zapis lokalny',
    renewListing: 'Odnów ogłoszenie',
    renewListingHint: 'Ogłoszenie będzie aktywne przez kolejne 41 dni',
    listingExpiredBanner: 'Termin ogłoszenia wygasł. Odnów, aby ponownie pokazać auto.',
    listingExpiresSoonBanner: 'Ogłoszenie wkrótce wygasa. Odnów publikację, żeby nie stracić widoczności.',
    sectionIdentity: 'Identyfikacja pojazdu',
    sectionSpecs: 'Specyfikacja techniczna',
    sectionLogistics: 'Zakup i logistyka',
    sectionCondition: 'Stan i kompletność',
    sectionPublication: 'Publikacja w autach dostępnych',
    sectionGallery: 'Galeria zdjęć i zapis wizualny',
    sectionNotes: 'Opis, historia i notatki',
    fieldTitle: 'Nazwa karty',
    fieldMake: 'Marka',
    fieldModel: 'Model',
    fieldYear: 'Rok',
    fieldVin: 'VIN',
    fieldLotNumber: 'Numer lotu',
    fieldStockNumber: 'Numer wewnętrzny',
    fieldSourceUrl: 'Link źródłowy',
    fieldAuction: 'Aukcja / źródło',
    fieldStatus: 'Status',
    fieldBodyStyle: 'Typ nadwozia',
    fieldBodyCode: 'Kod nadwozia',
    fieldGeneration: 'Generacja',
    fieldTrim: 'Wersja wyposażenia',
    fieldColorExterior: 'Kolor nadwozia',
    fieldColorInterior: 'Kolor wnętrza',
    fieldEngineVolume: 'Pojemność silnika',
    fieldEngineCode: 'Kod silnika',
    fieldEnginePowerHp: 'Moc, KM',
    fieldFuelType: 'Rodzaj paliwa',
    fieldDrivetrain: 'Napęd',
    fieldTransmission: 'Skrzynia biegów',
    fieldMileageKm: 'Przebieg',
    fieldOdometerUnit: 'Jednostka przebiegu',
    fieldLocation: 'Lokalizacja auta',
    fieldCountryOfOrigin: 'Kraj pochodzenia',
    fieldImportDestination: 'Kraj docelowy',
    fieldOwnershipType: 'Forma własności',
    fieldKeysStatus: 'Kluczyki',
    fieldStartCondition: 'Stan uruchomienia',
    fieldDamagePrimary: 'Uszkodzenie główne',
    fieldDamageSecondary: 'Uszkodzenie dodatkowe',
    fieldPublicationStatus: 'Status publikacji',
    fieldPublicTitle: 'Publiczny tytuł',
    fieldPublicSlug: 'Publiczny slug',
    fieldPublicDescription: 'Krótki opis do katalogu',
    fieldPublicPriceUsd: 'Cena publiczna, USD',
    fieldPublicEstimateUsd: 'Szacowana cena, USD',
    fieldPublicBadge: 'Badge / etykieta',
    fieldPublicHotOffer: 'Oznacz jako hot offer',
    fieldRepairEstimateUsd: 'Koszt naprawy, USD',
    fieldTargetBudgetUsd: 'Budżet docelowy, USD',
    fieldPurchasePriceUsd: 'Cena zakupu, USD',
    fieldCustomsAndFeesUsd: 'Cło i opłaty, USD',
    fieldSellerName: 'Sprzedawca / kontakt',
    fieldSellerPhone: 'Telefon sprzedawcy',
    fieldDescription: 'Krótki opis pojazdu',
    fieldServiceHistory: 'Historia serwisowa',
    fieldModifications: 'Modyfikacje i tuning',
    fieldNotes: 'Notatki менеджера',
    photoCountLabel: 'zdjęć',
    carCountLabel: 'aut',
    statusLabels: {
      draft: 'Szkic',
      research: 'Analiza',
      bidding: 'W procesie',
      won: 'Wygrane',
      shipping: 'Transport',
      repair: 'Naprawa',
      ready: 'Gotowe',
      sold: 'Sprzedane',
    },
    publicationStatusLabels: {
      private: 'Prywatne',
      published: 'Opublikowane',
      pending_transit: 'Oczekuje (w drodze)',
      pending_stock: 'Oczekuje (w nalichii)',
      rejected: 'Odrzucone',
    },
  },
}

export function getCabinetCopy(locale: Locale) {
  return copy[locale]
}